#!/usr/bin/env python3
"""Compare DFAH behavioral metrics against conventional accuracy.

This is a no-LLM post-processing analysis for the NeurIPS E&D paper. It asks
whether the benchmark's behavioral metrics are merely proxies for conventional
modal-decision accuracy. The output supports the paper's claim that accuracy
and process consistency are distinct evaluation dimensions.

Inputs are generated by existing paper-support scripts:
  - results/dfah_model_level.csv
  - results/dfah_model_accuracy.csv
  - results/dfah_dcb_across_case_model.csv
  - results/dfah_kappa_model_level.csv

Usage:
    python3 scripts/compute_accuracy_metric_correlations.py
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd


REPO_ROOT = Path(__file__).resolve().parent.parent
RESULTS_DIR = REPO_ROOT / "results"
OUTPUT_CSV = RESULTS_DIR / "dfah_accuracy_metric_correlations.csv"

SEED = 42
N_PERMUTATIONS = 10000


@dataclass(frozen=True)
class MetricSpec:
    """Column and display metadata for one correlation row."""

    metric: str
    display: str
    column: str
    interpretation: str


METRICS = [
    MetricSpec("DAR", "Decision agreement", "mean_dar", "within-case outcome stability"),
    MetricSpec("Kappa", "Chance-corrected agreement", "mean_kappa", "agreement beyond model marginals"),
    MetricSpec("TAR", "Trajectory agreement", "mean_tar", "tool-path stability"),
    MetricSpec("Gap", "DAR-TAR gap", "mean_dar_tar_gap", "hidden trajectory instability"),
    MetricSpec("DCB", "Decision concentration", "mean_dcb_across_case", "across-case modal-decision concentration"),
    MetricSpec("ECD", "Evidence contact divergence", "mean_ecd", "evidence-contact instability"),
]


def average_ranks(values: np.ndarray) -> np.ndarray:
    """Return average ranks for a 1D array, handling ties deterministically."""
    order = np.argsort(values, kind="mergesort")
    sorted_values = values[order]
    ranks = np.empty(len(values), dtype=float)

    i = 0
    while i < len(values):
        j = i + 1
        while j < len(values) and sorted_values[j] == sorted_values[i]:
            j += 1
        # Ranks are 1-indexed; tied values receive their average rank.
        rank = (i + 1 + j) / 2.0
        ranks[order[i:j]] = rank
        i = j
    return ranks


def pearson_corr(x: np.ndarray, y: np.ndarray) -> float:
    """Compute Pearson correlation without adding a scipy dependency."""
    if len(x) < 2:
        return float("nan")
    x0 = x - np.mean(x)
    y0 = y - np.mean(y)
    denom = np.sqrt(np.sum(x0 * x0) * np.sum(y0 * y0))
    if denom == 0:
        return float("nan")
    return float(np.sum(x0 * y0) / denom)


def spearman_corr(x: np.ndarray, y: np.ndarray) -> float:
    """Compute Spearman rank correlation with average ranks for ties."""
    return pearson_corr(average_ranks(x), average_ranks(y))


def permutation_p_value(x: np.ndarray, y: np.ndarray, observed: float) -> float:
    """Two-sided permutation p-value for Spearman correlation."""
    if np.isnan(observed) or len(x) < 3:
        return float("nan")
    rng = np.random.default_rng(SEED)
    count = 0
    for _ in range(N_PERMUTATIONS):
        permuted_y = rng.permutation(y)
        rho = spearman_corr(x, permuted_y)
        if abs(rho) >= abs(observed):
            count += 1
    return float((count + 1) / (N_PERMUTATIONS + 1))


def load_model_table() -> pd.DataFrame:
    """Join model-level behavioral metrics with canonical accuracy."""
    model = pd.read_csv(RESULTS_DIR / "dfah_model_level.csv")
    accuracy = pd.read_csv(RESULTS_DIR / "dfah_model_accuracy.csv")
    dcb = pd.read_csv(RESULTS_DIR / "dfah_dcb_across_case_model.csv")
    kappa = pd.read_csv(RESULTS_DIR / "dfah_kappa_model_level.csv")

    return (
        model.merge(
            accuracy[["model", "model_display", "task_weighted_accuracy_pct"]],
            on="model",
            how="inner",
        )
        .merge(dcb[["model", "mean_dcb_across_case"]], on="model", how="left")
        .merge(kappa[["model", "mean_kappa"]], on="model", how="left")
    )


def main() -> None:
    df = load_model_table()
    rows = []

    for spec in METRICS:
        sub = df[[spec.column, "task_weighted_accuracy_pct"]].dropna()
        x = sub[spec.column].to_numpy(dtype=float)
        y = sub["task_weighted_accuracy_pct"].to_numpy(dtype=float)

        rho = spearman_corr(x, y)
        pearson = pearson_corr(x, y)
        p_value = permutation_p_value(x, y, rho)
        rows.append(
            {
                "metric": spec.metric,
                "display": spec.display,
                "interpretation": spec.interpretation,
                "n_models": len(sub),
                "spearman_rho_vs_accuracy": rho,
                "permutation_p_value": p_value,
                "pearson_r_vs_accuracy": pearson,
            }
        )

    out = pd.DataFrame(rows)
    out.to_csv(OUTPUT_CSV, index=False)

    print(f"Wrote {OUTPUT_CSV}")
    print("\nDFAH metric correlation with conventional modal-decision accuracy:")
    print(
        out[
            [
                "metric",
                "n_models",
                "spearman_rho_vs_accuracy",
                "permutation_p_value",
                "pearson_r_vs_accuracy",
            ]
        ].to_string(
            index=False,
            formatters={
                "spearman_rho_vs_accuracy": "{:.3f}".format,
                "permutation_p_value": "{:.3f}".format,
                "pearson_r_vs_accuracy": "{:.3f}".format,
            },
        )
    )

    print("\nLaTeX rows:")
    for _, row in out.iterrows():
        print(
            f"{row['metric']} & {int(row['n_models'])} & "
            f"{row['spearman_rho_vs_accuracy']:.3f} & "
            f"{row['permutation_p_value']:.3f} & "
            f"{row['pearson_r_vs_accuracy']:.3f} \\\\"
        )


if __name__ == "__main__":
    main()
